name: Bug Report (错误报告)

description: >
  提交错误报告时，请尽可能提供详细信息，帮助我们快速定位并解决问题。  
  Please provide as much detail as possible when submitting a bug report to help us quickly identify and fix the issue.

title: "[Bug Report] (错误报告)"

labels:
  - bug
  - needs-triage

assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **注意：** 请先检查现有的 Issues，确保该问题尚未被报告。  
        **Note:** Please check the existing Issues to ensure the problem hasn't already been reported.

  - type: input
    attributes:
      label: "问题描述 (Bug Description)"
      description: "简要描述问题及其发生的情况。/ Briefly describe the issue and its occurrence."
      placeholder: "例如：程序崩溃，无法启动等 / For example: The app crashes, won't start, etc."
      required: true

  - type: input
    attributes:
      label: "重现步骤 (Steps to Reproduce)"
      description: "提供复现问题的步骤。/ Provide the steps to reproduce the issue."
      placeholder: "例如：1. 启动应用 2. 点击按钮A 3. 错误发生 / For example: 1. Launch the app 2. Click button A 3. Error occurs"
      required: true

  - type: input
    attributes:
      label: "实际行为 (Actual Behavior)"
      description: "描述问题发生时程序的实际行为。/ Describe the actual behavior when the issue occurs."
      placeholder: "例如：程序崩溃，页面无法显示等 / For example: The app crashes, the page won't load, etc."
      required: true

  - type: input
    attributes:
      label: "操作系统版本 (Operating System and Version)"
      description: "提供操作系统及其版本信息。/ Provide the operating system and version."
      placeholder: "例如：Ubuntu 22.04, Windows 10 等 / For example: Ubuntu 22.04, Windows 10, etc."
      required: true

  - type: input
    attributes:
      label: "启动器版本号 (Launcher Version)"
      description: "提供启动器的版本号。/ Provide the launcher version."
      placeholder: "例如：25.8.3-alpha / For example: 25.8.3-alpha"
      required: true

  - type: input
    attributes:
      label: "日志信息 (Logs)"
      description: "如果有相关日志，请附上。/ Please attach any relevant logs if available."
      placeholder: "例如：崩溃日志或错误日志 / For example: Crash log or error log."
      required: false

  - type: input
    attributes:
      label: "其他信息 (Additional Information)"
      description: "提供任何可能有助于解决问题的其他信息。/ Provide any other information that may assist in resolving the issue."
      placeholder: "例如：遇到问题时的其他环境配置等 / For example: Additional environment settings when the issue occurs."
      required: false

  - type: checkbox
    attributes:
      label: "确认已尝试以下解决步骤 (Confirm the following steps have been tried)"
      description: "请勾选已尝试的步骤。/ Check all the steps you've already tried."
      required: true
      options:
        - label: "重置整个启动器 / Resetting the entire launcher"
        - label: "清理缓存 / Clearing the cache"
        - label: "更新到最新版本 / Updating to the latest version"
        - label: "其他 / Other"
