name: Bug Report (错误报告)

description: >
  提交错误报告时，请尽可能提供详细信息，帮助我们快速定位并解决问题。  
  Please provide as much detail as possible when submitting a bug report to help us quickly identify and fix the issue.

title: "[Bug Report] (错误报告)"

labels:
  - bug
  - needs-triage

assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **注意：** 请先检查现有的 Issues，确保该问题尚未被报告。  
        **Note:** Please check the existing Issues to ensure the problem hasn't already been reported.

  - type: input
    id: launcher_version
    attributes:
      label: "启动器版本 (Launcher Version)"
      description: "请输入您使用的启动器版本。/ Please enter the launcher version you are using."
      placeholder: "例如：25.8.3-alpha / For example: 25.8.3-alpha"
    validations:
      required: true

  - type: input
    id: system_version
    attributes:
      label: "系统版本 (System Version)"
      description: "请输入您的操作系统版本。/ Please enter your operating system version."
      placeholder: "例如：Windows 10,Ubuntu 22.04 / For example: Windows 10,Ubuntu 22.04."
    validations:
      required: true

  - type: input
    id: bug_description
    attributes:
      label: "问题描述 (Bug Description)"
      description: "简要描述问题及其发生的情况。/ Briefly describe the issue and its occurrence."
      placeholder: "例如：程序崩溃，无法启动等 / For example: The app crashes, won't start, etc."
    validations:
      required: true

  - type: input
    id: steps_to_reproduce
    attributes:
      label: "重现步骤 (Steps to Reproduce)"
      description: "提供复现问题的步骤。/ Provide the steps to reproduce the issue."
      placeholder: "例如：1. 启动应用 2. 点击按钮A 3. 错误发生 / For example: 1. Launch the app 2. Click button A 3. Error happens."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 你是否检查过该问题是否已经报告？  
        Have you checked if the issue has already been reported?
        - [ ] 是 / Yes
        - [ ] 否 / No