name: BUG Report / BUG 反馈
description: 'Report a bug / 反馈一个 Bug'
labels: [Bug]
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type / 问题类型
      options:
        - 'Game Issue / 游戏问题'
        - 'Launcher Issue / 启动器问题'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description / 问题描述
      description: |
        Detail describe the issue you encountered.
        详细地描述出你所遇到的问题
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Log File / 日志文件
      description: |
        You need to upload the latest log file to help me locate the problem
        您需要在这里上传最近的日志文件，方便我定位问题
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos / 截图或视频
      description: |
        Upload a screenshot or video of the last time you encountered this problem
        上传最近一次遇到此 Bug 的截图或视频
    validations:
      required: false

  - type: textarea
    id: repetition
    attributes:
      label: Reproduction Steps / 复现步骤
      description: |
        Please provide as many steps as possible to reproduce this bug so that I can locate the problem.
        复现此 Bug 的步骤，请尽量详细一点，方便我定位问题
      placeholder: |
        1. xxx
        2. xxx
        ... *(steps to reproduce the issue / 复现问题的一些操作)*
      render: markdown
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: OpenBCLCore Version / OpenBCLCore 版本号
      description: |
        Which version of OpenBCLCore did you encounter this issue in?
        遇到此 Bug 的版本是?
      placeholder: 1.0.0-Dev
    validations:
      required: true

  - type: input
    id: device-info
    attributes:
      label: Device Information / 设备信息
      description: |
        Providing detailed information about the device will help me troubleshoot the issue.
        提供设备的详细信息，有助于我排查问题。
      placeholder: Linux amd64
    validations:
      required: true

  - type: checkboxes
    id: check-issue
    attributes:
      label: This issue has not been reported before / 这个问题貌似还没有人反馈过
      options:
        - label: I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈
          required: true
